# Elenchi territoriali usati da Kiron.
# Aggiornati al quadro ISTAT 2026; Sardegna adeguata al nuovo assetto valido dal 1/1/2026.

REGIONI_PROVINCE = {'Piemonte': ['Torino', 'Vercelli', 'Novara', 'Cuneo', 'Asti', 'Alessandria', 'Biella', 'Verbano-Cusio-Ossola'], "Valle d'Aosta/Vallée d'Aoste": ["Valle d'Aosta/Vallée d'Aoste"], 'Lombardia': ['Varese', 'Como', 'Sondrio', 'Milano', 'Bergamo', 'Brescia', 'Pavia', 'Cremona', 'Mantova', 'Lecco', 'Lodi', 'Monza e della Brianza'], 'Trentino-Alto Adige/Südtirol': ['Bolzano/Bozen', 'Trento'], 'Veneto': ['Verona', 'Vicenza', 'Belluno', 'Treviso', 'Venezia', 'Padova', 'Rovigo'], 'Friuli-Venezia Giulia': ['Udine', 'Gorizia', 'Trieste', 'Pordenone'], 'Liguria': ['Imperia', 'Savona', 'Genova', 'La Spezia'], 'Emilia-Romagna': ['Piacenza', 'Parma', "Reggio nell'Emilia", 'Modena', 'Bologna', 'Ferrara', 'Ravenna', 'Forlì-Cesena', 'Rimini'], 'Toscana': ['Massa-Carrara', 'Lucca', 'Pistoia', 'Firenze', 'Livorno', 'Pisa', 'Arezzo', 'Siena', 'Grosseto', 'Prato'], 'Umbria': ['Perugia', 'Terni'], 'Marche': ['Pesaro e Urbino', 'Ancona', 'Macerata', 'Ascoli Piceno', 'Fermo'], 'Lazio': ['Viterbo', 'Rieti', 'Roma', 'Latina', 'Frosinone'], 'Abruzzo': ["L'Aquila", 'Teramo', 'Pescara', 'Chieti'], 'Molise': ['Campobasso', 'Isernia'], 'Campania': ['Caserta', 'Benevento', 'Napoli', 'Avellino', 'Salerno'], 'Puglia': ['Foggia', 'Bari', 'Taranto', 'Brindisi', 'Lecce', 'Barletta-Andria-Trani'], 'Basilicata': ['Potenza', 'Matera'], 'Calabria': ['Cosenza', 'Catanzaro', 'Reggio di Calabria', 'Crotone', 'Vibo Valentia'], 'Sicilia': ['Trapani', 'Palermo', 'Messina', 'Agrigento', 'Caltanissetta', 'Enna', 'Catania', 'Ragusa', 'Siracusa'], 'Sardegna': ['Sassari', 'Gallura Nord-Est Sardegna', 'Nuoro', 'Oristano', 'Ogliastra', 'Medio Campidano', 'Cagliari', 'Sulcis Iglesiente']}

AREA_PER_REGIONE = {'Piemonte': 'Nord', "Valle d'Aosta/Vallée d'Aoste": 'Nord', 'Lombardia': 'Nord', 'Trentino-Alto Adige/Südtirol': 'Nord', 'Veneto': 'Nord', 'Friuli-Venezia Giulia': 'Nord', 'Liguria': 'Nord', 'Emilia-Romagna': 'Nord', 'Toscana': 'Centro', 'Umbria': 'Centro', 'Marche': 'Centro', 'Lazio': 'Centro', 'Abruzzo': 'Sud', 'Molise': 'Sud', 'Campania': 'Sud', 'Puglia': 'Sud', 'Basilicata': 'Sud', 'Calabria': 'Sud', 'Sicilia': 'Sud', 'Sardegna': 'Sud'}

REGIONI = list(REGIONI_PROVINCE.keys())
PROVINCE = [p for values in REGIONI_PROVINCE.values() for p in values]
